runtime: php73

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:/QKGHdQ4IjP7yDsHeC2XqFp1lMv0+FNT9xeQBYYkf0s=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: ordenes
  DB_USERNAME: root
  DB_PASSWORD: Dgu3rr4-SP20
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/ordenes-spectra:us-east1:ordenesdb"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"



